version: '1.0'

jobs:

  runs-on: java-ci-base2:latest

  setup:
    steps:
      - name: Clean Workspace
        run: rm -rf workspace/app

      - name: Clone Repository
        run: git clone https://github.com/Sectani/Java-Maven-Application workspace/app

      - name: Install Dependencies
        working-directory: workspace/app
        run: mvn clean install -DskipTests

  test:
    depends-on: setup
    steps:
      - name: Run Tests
        working-directory: workspace/app
        run: |
          mvn test
          mkdir -p /artifacts/test-reports
          cp -r target/surefire-reports/* /artifacts/test-reports/

  build:
    depends-on: test
    steps:
      - name: Build Project
        working-directory: workspace/app
        run: mvn clean package -DskipTests

      - name: Save Artifact
        run: cp target/*.jar /artifacts/

  docker_push:
    depends-on: build
    steps:
      - name: Build Docker Image
        working-directory: workspace/app/
        run: docker build -t sectani/java-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_EAMIL" --password-stdin

      - name: Push Docker Image
        run: docker push sectani/java-app:latest

  Setup Kubeconfig:
      depends-on: docker_push
      steps:
        - name: Setup Kubeconfig
          working-directory: workspace/app
          run: |
            mkdir -p ~/.kube
            echo "$KUBECONFIG_CONTENT" > ~/.kube/config
  
        - name: Deploy
          run: |
            kubectl apply -f deployment.yaml
  
        - name: Debug
          run: |
            kubectl get nodes
