apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-application
  template:
    metadata:
      labels:
        app: java-maven-application
    spec:
      containers:
        - name: java-maven-application
          image: sectani/java-app:latest
          ports:
            - containerPort: 9099
---
apiVersion: v1
kind: Service
metadata:
  name: java-maven-application-service
spec:
  type: NodePort
  selector:
    app: java-maven-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9099
      nodePort: 30080